# Generated by Django 4.1.7 on 2023-04-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_comn_alter_emp_mgr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='DEPTNo',
            new_name='DEPTNO',
        ),
    ]
