# Generated by Django 4.1.7 on 2023-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_deptno_emp_deptno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='COMN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='MGR',
            field=models.IntegerField(null=True),
        ),
    ]
